language : node_js
node_js :
 - stable
os:
 - linux
 - osx
install:
 - npm install
before_script:
 - npm run transpile
script:
 - npm run test
# Send coverage data to Coveralls
after_script: "npm run cover"
