language : node_js
node_js:
 - node
os:
 - linux
 - osx
install:
 - npm install
before_script:
 - npm run transpile
script:
 - npm run nyc
# Send coverage data to Coveralls
after_script: "npm run cover"
