language : node_js
node_js :
 - stable
install:
 - npm install
before_script:
 - npm run transpile
script:
 - npm cover
# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"