name: Test
on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
        pnpm-version: [8.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node dependencies
        run: pnpm install
        
      - name: Transpile code
        run: pnpm run transpile
        
      - name: Run tests and generate coverage report
        run: pnpm run nyc
       
      - name: Send coverage report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Send coverage report to Codecov
        uses: Atrox/codecov-action@v0.1.3
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  
       
      - name: Send coverage report to Code Climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }} 

